services:
  memora-postgres-db:
    container_name: memora-postgres-db
    image: postgres:17
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_INNER_PORT}"
    networks:
      - memora
    volumes:
      - memora_pg_data:/var/lib/postgresql/data

volumes:
  memora_pg_data:

networks:
  memora:
    name: memora-network
    driver: bridge
